### PR TITLE
API: support for xgboost

### LINKED ISSUE #164: Native XGBoost support
**Is your feature request related to a problem? Please describe.**
XGboost is currently not natively supported by sklearndf

**Describe the solution you'd like**
Currently, users can fix this individually by using the `make_df_regressor` wrapper

```
from xgboost import XGBRegressor
from sklearndf.wrapper import make_df_regressor
XGBRegressorDF = make_df_regressor(XGBRegressor)
```

It would be desirable to move this directly into `sklearnf.regression` and `sklearn.classification` for the XGboost regressor/classifier respectively. 

To avoid additional dependencies, we should make an assertion that `xgboost` must be installed if the `XGBRegressorDF`/`XGBClassifierDF` is used. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by mtsokol**

### CODE REVIEW

**Comment by j-ittner** [comment]
Hi @mtsokol before continuing this, can I suggest you review #214 then merge it into your branch? This may affect your code.

**Comment by j-ittner** [comment]
@mtsokol there was an obscure bug in pytools that caused a problem here. It is fixed in BCG-Gamma/pytools#333. Suggest you review then we release pytools 2.0.1. This PR should run successfully afterwards.

**Comment by mtsokol** [comment]
> @mtsokol there was an obscure bug in pytools that caused a problem here. It is fixed in [BCG-Gamma/pytools#333](https://github.com/BCG-Gamma/pytools/pull/333). Suggest you review then we release pytools 2.0.1. This PR should run successfully afterwards.

@j-ittner Thanks! The PR is ready and I also noticed a bug in pytools but didn't explore it. Reviewed!

**Review by j-ittner — APPROVED** [review]
Looks great, many thanks!

**Pull request merged**
